#pragma once

#include "FAST_RUNTIME_TYPE_CASTING_ROOT_Internals.h"
#include "FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS_Macros.h"



class FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS
{
	FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS_BODY

public:
	FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS();
	FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS(const FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS&);
	FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS(FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS&&) noexcept;
	FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS& operator=(const FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS&);
	FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS& operator=(FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS&&) noexcept;
	virtual ~FAST_RUNTIME_TYPE_CASTING_ROOT_CLASS();

	

};


